services:
  exporter:
    build: .
    ports:
      - 6533:6533
    volumes:
      - "C:/Users/Ernst.Haagsman/GolandProjects/HyperBackupExporter/testfiles2/backup.last:/var/packages/HyperBackup/var/last_result/backup.last:ro"
      - "C:/Users/Ernst.Haagsman/GolandProjects/HyperBackupExporter/testfiles2/synobackup.conf:/var/packages/HyperBackup/etc/synobackup.conf:ro"
